# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

version: 1.1.4

data-provider:
  check_updates:
    runtime: nodejs:18
  package:
    runtime: nodejs:18
  react-query:
    runtime: nodejs:18
  specs:
    runtime: nodejs:18
  src:
    runtime: nodejs:18
  tsconfig:
    runtime: nodejs:18
  tsconfig.spec:
    runtime: nodejs:18
