# App Specification for LibreChat

data-provider:
  check_updates:
    runtime: nodejs:18
  package:
    runtime: nodejs:18
  react-query:
    runtime: nodejs:18
  specs:
    runtime: nodejs:18
  src:
    runtime: nodejs:18
  tsconfig:
    runtime: nodejs:18
  tsconfig.spec:
    runtime: nodejs:18
    
name: librechat
region: nyc

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

ingress:
  rules:
    - component:
        name: api
      match:
        path:
          prefix: /api
    - component:
        name: website
      cors:
        allow_origins:
          - prefix: https://internal.example-app.com
      match:
        path:
          prefix: /

services:
  - environment_slug: go
    github:
      branch: main
      deploy_on_push: true
      repo: public-github-user/librechat-api
    http_port: 8080
    instance_count: 2
    instance_size_slug: professional-xs
    name: api
    run_command: bin/api
    source_dir: /

static_sites:
  - environment_slug: html
    github:
      branch: master
      deploy_on_push: true
      repo: public-github-user/librechat-website
    name: website
    source_dir: /
